#!/usr/bin/env python
from bars import vuBarsEffect
from fire import fireEffect
from scroll import scrollImage, scrollText, scrollSequence
from multiEffect import multiEffect
from runEffects import runEffect,im
import Image

def error(text):
	global im
	im = scrollText(text,im)

def parse(lines):
	global im
	lineNo = 0
	for line in lines:
		lineNo += 1
		line = line.strip()
		if not line or line[0]=='#':
			# Skip blank lines and comments
			continue
		effect, parameter = line.split(':',1)
		if effect=="text":
			im = runEffect(scrollText(parameter,im))
		elif effect=="fire":
			if not parameter.isdigit():
				error("Fire effect takes a number")
			im = runEffect(fireEffect(im,100),100)
		elif effect=="bars":
			if not parameter.isdigit():
				error("Bars effect takes a number")
			im = runEffect(multiEffect(im, [
					( vuBarsEffect(), (0,0,9,9) ),
					( vuBarsEffect(), (11,0,20,9) ),
					( vuBarsEffect(), (22,0,31,9) ),
					( vuBarsEffect(), (33,0,42,9) ),
					( vuBarsEffect(), (44,0,53,9) ),
					( vuBarsEffect(), (55,0,64,9) ),
			]),int(parameter))
		elif effect=="textfire":
			im = runEffect(multiEffect(im, [
					( fireEffect(Image.new('RGB', (9,9))), (0,0,9,9) ),
					( scrollText(parameter, Image.new('RGB',(42,9))), (11,0,53,9) ),
					( fireEffect(Image.new('RGB', (9,9))), (55,0,64,9) ),
			]))
		elif effect=="textbars":
			im = runEffect(multiEffect(im, [
					( vuBarsEffect(), (0,0,9,9) ),
					( scrollText(parameter, Image.new('RGB',(42,9))), (11,0,53,9) ),
					( vuBarsEffect(), (55,0,64,9) ),
			]))
		elif effect=="image":
			scrollSequence([im,Image.open('images/'+parameter)])
		else:
			error("Unknown effect on line %s" % lineNo)

lines = list(open("sign.txt",'r'))
parse(lines)

